name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
        with:
            main-branch-name: master
            set-environment-variables-for-job: true
            error-on-no-successful-workflow: false
            last-successful-event: push
            working-directory: ./monorepo

#       - run: npx nx format:check
#       - run: npx nx affected -t lint --parallel=3
#       - run: npx nx affected -t test --parallel=3 --configuration=ci
#       - run: npx nx affected -t build --parallel=3
      - name: Setup and run tests
        working-directory: ./monorepo
        run: |
          ls
          pwd
          npm config set legacy-peer-deps true
          npm ci --force
          npx nx test express-app
